services:
  api:
    container_name: api
    image: api_express
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_USER=correamito
      - DB_PASSWORD=090903
      - DB_HOST=db
      - DB_PORT=5432
      - DB=products_management
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=correamito
      - POSTGRES_PASSWORD=090903
      - POSTGRES_DB=products_management
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
